---
resources:
- name: selenium-git-repo
  type: git
  source:
    uri: "https://github.com/pivotal-kahin-ng/selenium-example"

jobs:
- name: run-selenium-tests
  plan:
  - get: selenium-git-repo
    trigger: true
  - task: test
    privileged: true
    file: selenium-git-repo/ci/test.yml